server:
  port: 8888
spring:
  profiles:
    active: git
  application:
    name: "CONFIG-SERVER"
  cloud:
    config:
      server:
        git:
          uri: https://github.com/sarpio/microservice-eureka-sarpio/Config
          clone-on-start: true
          default-label: main
